networks:
  default:
    name: openbao-quickstarts

services:
  openssh:
    container_name: openssh
    image: linuxserver/openssh-server:latest
    environment:
      PUID: 1000
      PGID: 1000
      TZ: "Etc/UTC"
      PASSWORD_ACCESS: "false"
      USER_NAME: "alice"
      LOG_STDOUT: "true"
    ports:
      - "2222:2222"
    volumes:
      - ./config:/config:Z
    healthcheck:
      test: ["CMD-SHELL", "sshd.pam -T | grep -q 'port 22' || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 5

  openbao:
    container_name: openbao
    image: openbao/openbao:latest
    environment:
      BAO_ADDR: "http://127.0.0.1:8200"
      BAO_DEV_ROOT_TOKEN_ID: "root"
      BAO_TOKEN: "root"
    ports:
      - "8200:8200"
    command: server -dev
    healthcheck:
      test: ["CMD-SHELL", "bao status"]
      interval: 5s
      timeout: 5s
      retries: 5
    depends_on:
      openssh:
        condition: service_healthy
  
  client:
    container_name: client
    build: .
    environment:
      BAO_ADDR: http://openbao:8200
      BAO_TOKEN: "root"
    volumes:
      - ./keys:/keys:Z
    init: true
    depends_on:
      openbao:
        condition: service_healthy