networks:
  default:
    name: openbao-quickstarts

services:
  postgres:
    container_name: postgres
    image: postgres:18-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      ROOT_DB_USER: "openbao"
      ROOT_DB_PASSWORD: "openbao"
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-init.sh:/docker-entrypoint-initdb.d/postgres-init.sh:Z
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  openbao:
    container_name: openbao
    image: openbao/openbao:latest
    environment:
      BAO_ADDR: "http://127.0.0.1:8200"
      BAO_DEV_ROOT_TOKEN_ID: "root"
      BAO_TOKEN: "root"
      ROOT_DB_USER: "openbao"
      ROOT_DB_PASSWORD: "openbao"
      DB_USER: "app"
    ports:
      - "8200:8200"
    command: server -dev
    healthcheck:
      test: ["CMD-SHELL", "bao status"]
      interval: 5s
      timeout: 5s
      retries: 5
    depends_on:
      postgres:
        condition: service_healthy
  
  client:
    container_name: client
    build: .
    environment:
      BAO_ADDR: http://openbao:8200
      BAO_TOKEN: "root"
      DB_USER: "app"
    init: true
    depends_on:
      openbao:
        condition: service_healthy