# The domain(s) the provider is served from
domains = ["spire-server"]

insecure_addr = "0.0.0.0:8080"
allow_insecure_scheme = true

# Required: Point to your SPIRE Server or Workload API
server_api {
    address = "unix:///tmp/spire-server/private/api.sock"
}


# Optional: Set the log level to see incoming requests
log_level = "DEBUG"
