agent {
    data_dir = "/opt/spire/data"
    log_level = "DEBUG"
    trust_domain = "home.arpa"
    server_address = "spire-server"
    server_port = 8081

    # Insecure bootstrap is NOT appropriate for production use but is ok for 
    # simple testing/evaluation purposes.
    insecure_bootstrap = true
}

plugins {
   KeyManager "memory" {
       plugin_data {}
   }


    NodeAttestor "x509pop" {
        plugin_data {
            certificate_path = "/certs/spire-agent.pem"
            private_key_path = "/certs/spire-agent-key.pem"
        }
    }

    WorkloadAttestor "unix" {
        plugin_data {}
    }
}
