networks:
  default:
    name: openbao-quickstarts

services:
  openldap:
    container_name: openldap
    image: osixia/openldap
    command: --copy-service
    volumes:
      - ./bootstrap.ldif:/container/service/slapd/assets/config/bootstrap/ldif/custom/bootstrap.ldif
    healthcheck:
      test: ["CMD-SHELL", "ldapsearch -x -H ldap://localhost -b dc=example,dc=org -D 'cn=admin,dc=example,dc=org' -w admin '(objectClass=*)' || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 5

  openbao:
    container_name: openbao
    image: openbao/openbao:latest
    environment:
      BAO_DEV_ROOT_TOKEN_ID: "root"
      BAO_ADDR: "http://127.0.0.1:8200"
      BAO_TOKEN: "root"
    ports:
      - "8200:8200"
    command: server -dev
    healthcheck:
      test: ["CMD-SHELL", "bao status"]
      interval: 5s
      timeout: 5s
      retries: 5
    depends_on:
      openldap:
        condition: service_healthy
  
  client:
    container_name: client
    build: .
    environment:
      BAO_ADDR: "http://openbao:8200"
    depends_on:
      openbao:
        condition: service_healthy
    init: true